sudo: required

language: bash

services:
  - docker

install:
  - docker-compose run --rm app composer install -n
  - docker-compose build app

script:
  - docker-compose run --rm app

after_success:
  - docker images

after_error:
  - docker-compose logs

after_failure:
  - docker-compose logs

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  slack:
    secure: LdqXQm2lgCQo9PsefXO4xDPrYyQk3wvae1KQ8xTjPvbp95JtrEr1uTwCiuUmWvfG38Xx3DKj/fOcQ8kRxEKT6BYMsmrWfJ1xMHE2kymYkKjNN5Xys5gwgSfNYK2CwSi3NEzZ06oXhrNRgHIp1h7PZQsYWldL4zbAZZLl6fg2XeQNTrzc9d1cNxxZMh9L5taIQ9iWHAlMX6/SOxxNllUD/ODCuJzBJjeSApOs9sj7O4IvB/IkSCGLNIYc18ohL+WulEsobFiY1OhdfwU+eaclDQoqviiXDNoL/9/qS2YpkIfMssv901cRDFOVmj2tQSTGI4VpSbGoNSBmTzb9keqQHi+eDbRFw5qpF8zqDGp6Z6eAdyPFr4Lq3oVIgo4gU3qoNlzOFywriFu8MxQJBXuvr6iaAcunJS2VX1Bj5+iiZX3ZLCjc4KiP9YxMY4hVtmH6xiVYwH/F6Cf/Z6N/m5niZ0+I600s6EiF9eWnjPi3AHhFnUKVlBgM2GolVv2ev6R0SiZLi2lwWmGH5NAQhRvkxWrkl6SIxNsR6wQEugQOAHrgPxd0maJUmswgEX0B3/upp6FyoXeapD6hmJEYZsF4P0gjrg4bhH6ejIgT+PPWxQuU9N3341vhxhsKTisETVZuMRFTjBZcYzNWGnlbMocxRGHMhx/0kRKzONtmFaV7Vz8=
  email: false
