version: '2'
services:
  app:
    build: .
    image: keboola/processor-transpose
    volumes:
      - .:/code
    working_dir: /code
    entrypoint: bash -c "composer install && php vendor/bin/phpunit"
    tty: true
    stdin_open: true
